[project]
name = "trading-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "click>=8.2.0",
    "dotenv>=0.9.9",
    "gate-api>=6.97.2",
    "httpx>=0.28.1",
]
